# widgets.py

from custom_widgets.MainQWidget import MainQWidget
from custom_widgets.ButtonWidget import ButtonWidget
from custom_widgets.SettingsWidget import SettingsWidget
from custom_widgets.ConfigurableTree import ConfigurableTree
from custom_widgets.Text_display_panel import TextDisplayPanel
from custom_widgets.ImagesDisplayPanel import ImagesDisplayPanel
from custom_widgets.ConfirmDialog import ConfirmDialog
from custom_widgets.TerminalWidget import TerminalWidget
from custom_widgets.ErrorDialog import ErrorDialog
from custom_widgets.ContentSplitterWidget import ContentSplitterWidget
from custom_widgets.ColoredWidget import ColoredWidget
